---

- name: Login docker
  docker_login:
    registry_url: "{{ lookup('env','CI_REGISTRY') }}"
    username: "{{ lookup('env','CI_REGISTRY_USER') }}"
    password: "{{ lookup('env','CI_REGISTRY_PASSWORD') }}"
    state: "present"

- name: Run client side 
  docker_compose:
    project_name: "sample"
    pull: true
    recreate: always
    definition:
      version: '3.7'
      services:
        sample:
          image: "{{ lookup('env','SAMPLE_IMAGE_NAME') }}"
          container_name: "sample"
          restart: always
          network_mode: bridge
          environment:
            - SAMPLE_ENV_VAR={{ lookup('env', 'SAMPLE_ENV_VAR') }}
          ports:
            - 127.0.0.1:8080:80

  notify: Log out of DockerHub
